# Generated by Django 2.0.7 on 2018-07-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='blank',
        ),
    ]
