# Generated by Django 2.0.7 on 2018-07-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_test', '0003_basecreature_creature'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
