# Generated by Django 2.0.7 on 2018-07-13 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_test', '0004_creature_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creature',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_test.BaseCreature'),
        ),
    ]
