# Generated by Django 2.0.7 on 2018-07-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_test', '0005_auto_20180713_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
